import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
const openSans = Open_Sans({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Portofolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={openSans.className}>
        <div className="bg-home bg-no-repeat bg-cover bg-brown">{children}</div>
      </body>
    </html>
  );
}
